name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy DEV via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_DEPLOY_HOST }}
          username: ${{ secrets.DEV_DEPLOY_USER }}
          key: ${{ secrets.DEV_DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEV_DEPLOY_PORT }}
          script: |
            mkdir -p /root/torball-dev
            cd /root/torball-dev

            if [ ! -d torball.it ]; then
              git clone -b dev https://github.com/Schenna43lp1/torball.it.git
            fi

            cd torball.it
            git checkout dev
            git pull origin dev
            docker compose -f docker-compose.dev.yml up -d --build
            docker ps
